### ISSUE TITLE
[Feature][Track] KPM Import Tool

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl#526]
## Enhancement

The data and schema of other ecosystems, as well as the KCL configuration and schema conversion, are very important, considering the large number of YAML, Kustomize, and Helm configurations in the K8s ecosystem.

The import tool can be used import other data and schema to KCL. 

+ **APIs**
  + [x] OpenAPI https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genopenapi.go
  + [x] Terraform Provider Schema https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go
  + [x] JsonSchema https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
  + [x] Protobuf https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genpb.go
  + [x] Go Struct https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/gengo.go
  + [x] Json https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_json.go
  + [x] YAML https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_yaml.go
+ **CLI**
  + [ ] CLI Design: https://github.com/kcl-lang/kpm/issues/192

## Related Issues and Discussions

+ https://github.com/kcl-lang/kcl/issues/530
+ https://github.com/orgs/kcl-lang/discussions/651

**Comment by niconical** [comment]
# 背景

目前 KCL 语言可以被用作 KusionStack 的平台工程语言对 Kubernetes 和 Terraform 资源进行混合运维。但是需要手动书写 Terraform Schema 和 JsonSchema 转换为 KCL Schema 的程序，希望可以直接从 JsonSchema 和 Terraform Schema 转换为 KCL Schema 提升自动化效率。

# 目标

提供 KCL 语言工具支持如下内容：
- Terraform Schema 一键转换为 KCL Schema
- JsonSchema 一键转换为 KCL Schema
- JSON/YAML 配置数据一键转换为 KCL 配置
- 为所有实现撰写用户文档和参考手册
- [提高] 更多常用 Schema 一键转换为 KCL Schema

# 导师

徐鹏飞 | [xpf6677@gmail.com](mailto:xpf6677@gmail.com)

# 能力要求

- 熟悉 Go/Rust 等编程语言
- 熟悉常见的设计模式
- 熟悉 CLI 工具开发
- 熟悉 Markdown
- 熟悉 JSON/YAML 等配置
- 了解 Terraform
- 了解 Kubernetes

Ref: https://www.gitlink.org.cn/KusionStack/KCLVM/issues/4

**Comment by jakezhu9** [comment]
Thank you so much for giving me this opportunity to work on this task❤

I've already learned the basics of KCL, Terraform, and JSON Schema in order to accomplish it. My plan is to create a new tool called [kcl-importer](https://github.com/jakezhu9/kcl-importer) to achieve all our goals. At the moment, I've completed the initial framework of the tool, and I'm looking forward to converting JSON Schema over the next few weeks.

To make the tool more user-friendly, I think we can integrate its functionality into the kcl-go tool once it's fully developed. I've also noticed an issue that might be related to this tool ([API: support generate KCL configuration and schema from json/yaml](https://github.com/kcl-lang/kcl/issues/530)), and I'll do my best to resolve it, but it might take some time.

If anyone has any ideas or suggestions, please feel free to share them with me!
