### ISSUE TITLE
[Enhancement] integrate with KCL tools and KPM APIs

### ISSUE THREAD

**Issue by amyXia1994** [kcl-lang/kcl#891]
## Enhancement

cc @zong-zhe 

kpm tools need to integrate with all the existing kcl workflow. ref: #767 

known issues:
- [ ] #823

**Comment by zong-zhe** [comment]
I temporarily restored the previous symbolic links to make up for the blockage caused by this bug in PR https://github.com/kcl-lang/kpm/pull/215.

This PR will create a global symbolic link for each downloaded KCL package, which is used to ensure that the doc tool functions properly.

**NOTE: This is not a long-term solution, however, and you need to re-download the tripartite library every time you use the doc tool to keep the symbolic links up to date.**

**Comment by zong-zhe** [comment]
I will integrate with KCL tools and APIs next week.
